apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bppp4c1qq-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:69a7513477341c0bf39475b238d7a4d4cd0325bb@sha256:beeacb4f9f8da45677dcdf2ce2ac8b40da740f9e0c8ca84db16d59e215e58f66
          name: container-image
