apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bppp4c1qq-python
  janus-idp.io/tekton: bppp4c1qq-python
  backstage.io/kubernetes-id: bppp4c1qq-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bppp4c1qq-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
