apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bppp4c1qq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bppp4c1qq-python 
  name: bppp4c1qq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bppp4c1qq-python 
